version: "3.9"

services:
  wsi_mongo:
    image: mongo
    volumes:
      - wsi_data:/data/db
  web:
    build: .
    command: python3 app.py
    volumes:
      - /home/bioinfo/aperio:/images
    ports:
      - "2000:2000"
    environment:
      - DATABASE=wsi2ml
      - MONGO_ADDRESS=wsi_mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    depends_on:
      - wsi_db

volumes:
  wsi_data:

