events { }
http {
    client_max_body_size 100M;
    proxy_buffering off;
    proxy_ignore_client_abort on;

    upstream backend_server {
        server backend:2005;
    }

    upstream client_server {
        server web:80;
    }
    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_server/api/;
        }

        location / {
            proxy_pass http://client_server/;
        }
    }
}