"""empty message

Revision ID: 1d032a25ca1f
Revises: 1f22229c6133
Create Date: 2021-11-22 03:54:12.217306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d032a25ca1f'
down_revision = '1f22229c6133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotations_revised', type_='foreignkey')
    op.drop_constraint(None, 'annotations_revised', type_='foreignkey')
    op.create_foreign_key(None, 'annotations_revised', 'user_tasks', ['user_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'annotations_revised', 'annotations', ['annotation_id'], ['id'], ondelete='CASCADE')
    op.add_column('slides', sa.Column('properties_json', sa.Text(), nullable=True))
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'annotation_tasks', ['annotation_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks', 'revision_tasks', ['revision_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'revision_tasks', ['revision_task_id'], ['id'])
    op.create_foreign_key(None, 'user_tasks', 'annotation_tasks', ['annotation_task_id'], ['id'])
    op.drop_column('slides', 'properties_json')
    op.drop_constraint(None, 'annotations_revised', type_='foreignkey')
    op.drop_constraint(None, 'annotations_revised', type_='foreignkey')
    op.create_foreign_key(None, 'annotations_revised', 'annotations', ['annotation_id'], ['id'])
    op.create_foreign_key(None, 'annotations_revised', 'user_tasks', ['user_task_id'], ['id'])
    # ### end Alembic commands ###
