"""empty message

Revision ID: 1f22229c6133
Revises: 7fbef1ccbba6
Create Date: 2021-11-20 23:56:12.387359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f22229c6133'
down_revision = '7fbef1ccbba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slides', 'name')
    # ### end Alembic commands ###
