"""empty message

Revision ID: 20e5bf99dc97
Revises: 75bd045de58b
Create Date: 2022-02-27 13:59:33.768343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e5bf99dc97'
down_revision = '75bd045de58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_tasks', sa.Column('app_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_tasks', 'apps', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_column('user_tasks', 'app_id')
    op.drop_table('apps')
    # ### end Alembic commands ###
