"""empty message

Revision ID: 5387a7c8131b
Revises: 451002c1ef79
Create Date: 2021-10-11 02:16:10.754896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5387a7c8131b'
down_revision = '451002c1ef79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions_labelled', sa.Column('user_task_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'regions_labelled', type_='foreignkey')
    op.create_foreign_key(None, 'regions_labelled', 'user_tasks', ['user_task_id'], ['id'])
    op.drop_column('regions_labelled', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions_labelled', sa.Column('task_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'regions_labelled', type_='foreignkey')
    op.create_foreign_key(None, 'regions_labelled', 'tasks', ['task_id'], ['id'])
    op.drop_column('regions_labelled', 'user_task_id')
    # ### end Alembic commands ###
