"""empty message

Revision ID: 5ff69fcd2507
Revises: 
Create Date: 2021-11-12 03:31:08.008184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff69fcd2507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('folder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slides',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('annotation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('label_color', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('slide_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tasks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('annotation_task_id', sa.Integer(), nullable=True),
    sa.Column('revision_task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_task_id'], ['annotation_tasks.id'], ),
    sa.ForeignKeyConstraint(['revision_task_id'], ['revision_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions_labelled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=True),
    sa.Column('slide_id', sa.Text(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions_revised',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions_labelled.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions_revised')
    op.drop_table('regions_labelled')
    op.drop_table('user_tasks')
    op.drop_table('task_slides')
    op.drop_table('revision_tasks')
    op.drop_table('label')
    op.drop_table('annotation_tasks')
    op.drop_table('users')
    op.drop_table('slides')
    op.drop_table('projects')
    # ### end Alembic commands ###
