"""empty message

Revision ID: 7fbef1ccbba6
Revises: 798c0d1152f6
Create Date: 2021-11-13 23:40:26.174245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbef1ccbba6'
down_revision = '798c0d1152f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=True),
    sa.Column('slide_id', sa.Text(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations_revised',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=True),
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('regions_labelled')
    op.drop_table('regions_revised')
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot')
    op.create_table('regions_revised',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_task_id', sa.INTEGER(), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.Column('feedback', sa.INTEGER(), nullable=True),
    sa.Column('label_id', sa.INTEGER(), nullable=True),
    sa.Column('data_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions_labelled.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions_labelled',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_task_id', sa.INTEGER(), nullable=True),
    sa.Column('slide_id', sa.TEXT(), nullable=True),
    sa.Column('label_id', sa.INTEGER(), nullable=True),
    sa.Column('data_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('annotations_revised')
    op.drop_table('annotations')
    # ### end Alembic commands ###
